-- 기본키
CREATE TABLE MEM_PRIMARYKEY(
    MEM_NO NUMBER CONSTRAINT MEM_PK PRIMARY KEY,
    MEM_ID VARCHAR2(20) NOT NULL UNIQUE,
    MEM_PW VARCHAR2(20) NOT NULL,
    MEM_NAME VARCHAR2(20) NOT NULL,
    GENDER CHAR(3) CHECK (GENDER IN ('남', '여')),
    PHONE VARCHAR2(15),
    EMAIL VARCHAR2(50)
    -- CONSTRAINT MEM_PK PRIMARY KEY(MEM_NO)

);

INSERT INTO MEM_PRIMARYKEY 
VALUES (1, 'USER01', 'PASS01', 'OHJANGSEOK', '남', '010-1111-1111', 'AAA@NAVER.COM');
INSERT INTO MEM_PRIMARYKEY
VALUES (2, 'USER02', 'PASS01', 'SUMENG', '여', '010-2222-2222', 'BBB@NAVER.COM');
INSERT INTO MEM_PRIMARYKEY
VALUES (2, 'USER03', 'PASS03', 'UDONG', '여',NULL,NULL);
--> PK 중복
INSERT INTO MEM_PRIMARYKEY
VALUES (NULL, 'USER03', 'PASS03', 'UDONG', '여',NULL,NULL);
--> PK NULL X
INSERT INTO MEM_PRIMARYKEY
VALUES (3, 'USER03', 'PASS03', 'UDONG', '여',NULL,NULL);

CREATE TABLE MEM_PRIMARYKEY2(
    MEM_NO NUMBER,
    MEM_ID VARCHAR2(20),
    MEM_PW VARCHAR2(20) NOT NULL,
    MEM_NAME VARCHAR2(20) NOT NULL,
    GENDER CHAR(3) CHECK (GENDER IN ('남', '여')),
    PHONE VARCHAR2(15),
    EMAIL VARCHAR2(50),
    PRIMARY KEY(MEM_NO, MEM_ID) --> 복합키
);

INSERT INTO MEM_PRIMARYKEY2
VALUES (1, 'USER01', 'PASS01', 'HONG', '남', '010-1111-1111', 'hong@naver.com');
INSERT INTO MEM_PRIMARYKEY2
VALUES (2, 'USER01', 'PASS01', 'HONG', '남', '010-1111-1111', 'hong@naver.com');
INSERT INTO MEM_PRIMARYKEY2
VALUES (2, 'USER02', 'PASS01', 'HONG', '남', '010-1111-1111', 'hong@naver.com');

--------------------------------------------------------------------------------------------------
-- 외래키
CREATE TABLE MEM_GRADE(
    GRADE_CODE NUMBER PRIMARY KEY,
    GRADE_NAME VARCHAR2(30) NOT NULL

);

INSERT INTO MEM_GRADE VALUES (10, 'NORMAL');
INSERT INTO MEM_GRADE VALUES (20, 'SUPER');
INSERT INTO MEM_GRADE VALUES (30, 'EXCELLENT');

SELECT * FROM MEM_GRADE;

CREATE TABLE MEM(
    MEM_NO NUMBER PRIMARY KEY,
    MEM_ID VARCHAR2(20) NOT NULL UNIQUE,
    MEM_PW VARCHAR2(20) NOT NULL,
    MEM_NAME VARCHAR2(20) NOT NULL,
    GENDER CHAR(3) CHECK (GENDER IN ('남','여')),
    PHONE VARCHAR2(15),
    EMAIL VARCHAR2(50),
    GRADE_ID NUMBER, -- REFERENCES MEM_GRADE-- (GRADE_CODE) : PK로 지정했기 때문에 생략 가능
    FOREIGN KEY(GRADE_ID) REFERENCES MEM_GRADE

);

INSERT INTO MEM
VALUES (1, 'USER01', 'PASS01', 'HONG', NULL, NULL, NULL, 10);
INSERT INTO MEM
VALUES (2, 'USER02', 'PASS02', 'KIM', NULL, NULL, NULL, 20);
INSERT INTO MEM
VALUES (3, 'USER03', 'PASS03', 'LEE', NULL, NULL, NULL, 10);
INSERT INTO MEM
VALUES (4, 'USER04', 'PASS04', 'AN', NULL, NULL, NULL, NULL);
INSERT INTO MEM
VALUES (5, 'USER05', 'PASS05', 'SIN', NULL, NULL, NULL, 40);

SELECT * FROM MEM;
SELECT MEM_NAME, GRADE_NAME
FROM MEM M, MEM_GRADE G
WHERE M.GRADE_ID = G.GRADE_CODE(+);

SELECT MEM_NAME, GRADE_NAME
FROM MEM M
LEFT JOIN MEM_GRADE G ON GRADE_ID = GRADE_CODE;

DELETE FROM MEM_GRADE
WHERE GRADE_CODE = 10; --> 자식테이블에서 사용 중이라 삭제 불가

-- FOREIGN KEY 삭제 옵션
-- 기본 삭제 옵션 : ON DELETE RESTRICTED (삭제 제한)

DELETE FROM MEM_GRADE
WHERE GRADE_CODE = 30;

SELECT * FROM MEM_GRADE;
INSERT INTO MEM_GRADE VALUES (30, 'EXCELLENT');

DROP TABLE MEM;

-- 1) ON DELETE SET NULL : 부모데이터 삭제 시 해당 데이터를 사용하고 있는 자식데이터를 NULL값으로 변경
CREATE TABLE MEM(
    MEM_NO NUMBER PRIMARY KEY,
    MEM_ID VARCHAR2(20) NOT NULL UNIQUE,
    MEM_PW VARCHAR2(20) NOT NULL,
    MEM_NAME VARCHAR2(20) NOT NULL,
    GENDER CHAR(3) CHECK (GENDER IN ('남','여')),
    PHONE VARCHAR2(15),
    EMAIL VARCHAR2(50),
    GRADE_ID NUMBER REFERENCES MEM_GRADE ON DELETE SET NULL

);

INSERT INTO MEM
VALUES (1, 'USER01', 'PASS01', 'HONG', NULL, NULL, NULL, 10);
INSERT INTO MEM
VALUES (2, 'USER02', 'PASS02', 'KIM', NULL, NULL, NULL, 20);
INSERT INTO MEM
VALUES (3, 'USER03', 'PASS03', 'LEE', NULL, NULL, NULL, 10);
INSERT INTO MEM
VALUES (4, 'USER04', 'PASS04', 'AN', NULL, NULL, NULL, NULL);

SELECT * FROM MEM;

DELETE FROM MEM_GRADE
WHERE GRADE_CODE = 10;

SELECT * FROM MEM_GRADE;
ROLLBACK;
DROP TABLE MEM;

-- 2) ON DELETE CASCADE : 자식데이터도 삭제
CREATE TABLE MEM(
    MEM_NO NUMBER PRIMARY KEY,
    MEM_ID VARCHAR2(20) NOT NULL UNIQUE,
    MEM_PW VARCHAR2(20) NOT NULL,
    MEM_NAME VARCHAR2(20) NOT NULL,
    GENDER CHAR(3) CHECK (GENDER IN ('남','여')),
    PHONE VARCHAR2(15),
    EMAIL VARCHAR2(50),
    GRADE_ID NUMBER REFERENCES MEM_GRADE ON DELETE CASCADE

);

INSERT INTO MEM
VALUES (1, 'USER01', 'PASS01', 'HONG', NULL, NULL, NULL, 10);
INSERT INTO MEM
VALUES (2, 'USER02', 'PASS02', 'KIM', NULL, NULL, NULL, 20);
INSERT INTO MEM
VALUES (3, 'USER03', 'PASS03', 'LEE', NULL, NULL, NULL, 10);
INSERT INTO MEM
VALUES (4, 'USER04', 'PASS04', 'AN', NULL, NULL, NULL, NULL);

SELECT * FROM MEM;

DELETE FROM MEM_GRADE
WHERE GRADE_CODE = 10;

--------------------------------------------------------------------------------------------------
