/*
    < DML (DATA MANIPULATION LANGUAGE) >
    추가, 갱신, 제거

*/
-- 1. INSERT : 테이블에 새로운 행을 추가하는 구문 
-- INSERT INTO TABLE_NAME VALUES (값, 값, 값, ... );
-- : 테이블에 모든 컬럼에 대한 값을 INSERT하고자 할 때 사용, 컬럼 순번을 지켜서 VALUES에 값을 나열!!
INSERT INTO EMPLOYEE 
VALUES(900,'장채현','980914-2156477','jang_ch@kh.or.kr','01011112222', 
        'D1', 'J7',4000000,0.2,200,sysdate,null,default);
        
INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, EMP_NO, DEPT_CODE, JOB_CODE, HIRE_DATE)
VALUES (901, '강람보', '850918-2514655', 'D1', 'J7', sysdate);

CREATE TABLE EMP_01(
    EMP_ID NUMBER,
    EMP_NAME VARCHAR2(30),
    DEPT_TITLE VARCHAR2(20)
);

SELECT EMP_ID, EMP_NAME, DEPT_TITLE
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D ON (DEPT_CODE = DEPT_ID);

INSERT INTO EMP_01
    SELECT EMP_ID, EMP_NAME, DEPT_TITLE
    FROM EMPLOYEE E
    LEFT JOIN DEPARTMENT D ON (DEPT_CODE = DEPT_ID);

SELECT * FROM EMP_01;

-- 2. INSERT ALL
CREATE TABLE EMP_DEPT
AS SELECT EMP_ID, EMP_NAME, DEPT_CODE, HIRE_DATE FROM EMPLOYEE WHERE 1 != 1;
CREATE TABLE EMP_MANAGER
AS SELECT EMP_ID, EMP_NAME, MANAGER_ID FROM EMPLOYEE WHERE 1 <> 1;

SELECT EMP_ID, EMP_NAME, DEPT_CODE, HIRE_DATE, MANAGER_ID
FROM EMPLOYEE
WHERE DEPT_CODE = 'D1';

-- EMP_DEPT : 부서코드가 D1인 사원의 사번, 이름, 부서코드, 입사일 삽입
-- EMP_MANAGER : 부서코드가 D1인 사원의 사번, 이름, 사수사번 삽입
INSERT ALL
INTO EMP_DEPT VALUES (EMP_ID, EMP_NAME, DEPT_CODE, HIRE_DATE)
INTO EMP_MANAGER VALUES (EMP_ID, EMP_NAME, MANAGER_ID)
    SELECT EMP_ID, EMP_NAME, DEPT_CODE, HIRE_DATE, MANAGER_ID
    FROM EMPLOYEE
    WHERE DEPT_CODE = 'D1';

SELECT * FROM EMP_DEPT;
SELECT * FROM EMP_MANAGER;