-- 1. ALTER
-- 1-1) 컬럼 추가 (ADD)
SELECT * FROM DEPT_COPY;
ALTER TABLE DEPT_COPY ADD (CNAME VARCHAR2(20));
ALTER TABLE DEPT_COPY ADD (LNAME VARCHAR2(20) DEFAULT '한국');

-- 1-2) 컬럼 수정 (MODIFY)
SELECT * FROM DEPT_COPY;
ALTER TABLE DEPT_COPY MODIFY DEPT_ID CHAR(3);
ALTER TABLE DEPT_COPY MODIFY DEPT_ID NUMBER; --> X
ALTER TABLE DEPT_COPY MODIFY DEPT_TITLE VARCHAR2(10); --> X

ALTER TABLE DEPT_COPY
MODIFY DEPT_TITLE VARCHAR2(40)
MODIFY LOCATION_ID VARCHAR2(2)
MODIFY LNAME DEFAULT '미국';

-- 1-3) 컬럼 삭제 (DROP)
CREATE TABLE DEPT_COPY2
AS SELECT * FROM DEPT_COPY;

SELECT * FROM DEPT_COPY2;
ALTER TABLE DEPT_COPY2 DROP COLUMN DEPT_ID;
ALTER TABLE DEPT_COPY2 DROP COLUMN DEPT_TITLE;
ALTER TABLE DEPT_COPY2 DROP COLUMN CNAME DROP COLUMN LNAME; --> X
ALTER TABLE DEPT_COPY2 DROP COLUMN LOCATION_ID;
ALTER TABLE DEPARTMENT DROP COLUMN DEPT_ID; --> X

-- 2-1) 제약조건 추가 (ADD, MODIFY)
ALTER TABLE DEPT_COPY 
ADD CONSTRAINT DCOPY_PK PRIMARY KEY (DEPT_ID)
ADD CONSTRAINT DCOPY_UQ UNIQUE (DEPT_TITLE)
MODIFY LNAME CONSTRAINT DCOPY_NN NOT NULL;

-- 2-2) 제약조건 삭제 (DROP)
ALTER TABLE DEPT_COPY 
DROP CONSTRAINT DCOPY_PK;

ALTER TABLE DEPT_COPY
DROP CONSTRAINT DCOPY_UQ
DROP CONSTRAINT DCOPY_PK
MODIFY LNAME NULL;

-- 3-1) 컬럼명, 제약조건명, 테이블명 변경
SELECT * FROM DEPT_TEST;

ALTER TABLE DEPT_COPY RENAME COLUMN DEPT_TITLE TO DEPT_NAME;
ALTER TABLE DEPT_COPY RENAME CONSTRAINT SYS_C007138 TO DCOPY_LID_NN;
ALTER TABLE DEPT_COPY RENAME TO DEPT_TEST;



-- 2. DROP
DROP TABLE DEPT_TEST;

DROP TABLE DEPT_TEST CASCADE CONSTRAINT;


















