-- 3
SELECT BOOK_NO, BOOK_NM
FROM TB_BOOK
WHERE LENGTH(BOOK_NM)>=25;

-- 4
SELECT WRITER_NM, OFFICE_TELNO, HOME_TELNO, MOBILE_NO
FROM (SELECT ROWNUM, WRITER_NM, OFFICE_TELNO, HOME_TELNO, MOBILE_NO
FROM(SELECT *
FROM TB_WRITER
WHERE MOBILE_NO LIKE '019%'
AND WRITER_NM LIKE '김%'
ORDER BY 1 DESC))
WHERE ROWNUM = 1;

-- 5
SELECT COUNT(*) "작가(명)"
FROM TB_BOOK_AUTHOR
WHERE COMPOSE_TYPE = '옮김';

-- 6
SELECT COMPOSE_TYPE, COUNT(*)
FROM (SELECT * FROM TB_BOOK WHERE PAGE >= 300) B, (SELECT *
                 FROM TB_BOOK_AUTHOR
                 WHERE COMPOSE_TYPE IS NOT NULL) BA
WHERE B.BOOK_NO = BA.BOOK_NO
GROUP BY COMPOSE_TYPE;

-- 7
SELECT BOOK_NM, ISSUE_DATE, PUBLISHER_NM
FROM TB_BOOK
WHERE ISSUE_DATE = (SELECT MAX(ISSUE_DATE) FROM TB_BOOK);

-- 8
SELECT WRITER_NM "작가 이름", 합 "권 수"
FROM(SELECT ROWNUM, WRITER_NO, 합
FROM (SELECT WRITER_NO, COUNT(WRITER_NO) 합
FROM (SELECT * FROM TB_BOOK_AUTHOR WHERE COMPOSE_TYPE = '지음')
GROUP BY WRITER_NO
ORDER BY 2 DESC))
JOIN TB_WRITER USING (WRITER_NO)
WHERE ROWNUM <= 3;

-- 9
UPDATE TB_WRITER T
SET REGIST_DATE = (SELECT F 
                   FROM(SELECT WRITER_NO, MIN(ISSUE_DATE) F
                   FROM TB_BOOK_AUTHOR BA, TB_BOOK B
                   WHERE B.BOOK_NO = BA.BOOK_NO
                   GROUP BY WRITER_NO
                   ORDER BY 1) D
                   WHERE T.WRITER_NO = D.WRITER_NO);

-- 10
CREATE TABLE TB_BOOK_TRANSLATOR(
    BOOK_NO VARCHAR2(10),
    WRITER_NO VARCHAR2(10),
    TRANS_LANG VARCHAR2(60) DEFAULT NULL,
    CONSTRAINT FK_BOOK_TRANSLATOR_01 FOREIGN KEY(BOOK_NO) REFERENCES TB_BOOK(BOOK_NO),
    CONSTRAINT FK_BOOK_TRANSLATOR_02 FOREIGN KEY(WRITER_NO) REFERENCES TB_WRITER(WRITER_NO),
    CONSTRAINT PK_BOOK_TRANSLATOR PRIMARY KEY(BOOK_NO, WRITER_NO)
);
DROP TABLE TB_BOOK_TRANSLATOR;
-- 11
CREATE TABLE TEST
AS SELECT BOOK_NO, WRITER_NO 
         FROM TB_BOOK_AUTHOR
         WHERE COMPOSE_TYPE IN ('옮김', '역주', '편역', '공역');

ALTER TABLE TEST ADD C VARCHAR2(60);

INSERT INTO TB_BOOK_TRANSLATOR 
SELECT * FROM TEST;

DROP TABLE TEST;

DELETE FROM TB_BOOK_AUTHOR
WHERE COMPOSE_TYPE IN ('옮김', '역주', '편역', '공역');

COMMIT;

-- 12
SELECT BOOK_NM, WRITER_NM
FROM TB_BOOK_TRANSLATOR
JOIN TB_BOOK USING (BOOK_NO)
JOIN TB_WRITER USING (WRITER_NO)
WHERE SUBSTR(BOOK_NO,1,4) = 2007;

-- 13
CREATE OR REPLACE VIEW VW_BOOK_TRANSLATOR
AS SELECT BOOK_NM, WRITER_NM, ISSUE_DATE
   FROM TB_BOOK_TRANSLATOR
   JOIN TB_BOOK USING (BOOK_NO)
   JOIN TB_WRITER USING (WRITER_NO)
   WHERE SUBSTR(BOOK_NO,1,4) = 2007
WITH READ ONLY;

SELECT * FROM VW_BOOK_TRANSLATOR;

-- 14
INSERT INTO TB_PUBLISHER
VALUES ('춘 출판사', '02-6710-3737', DEFAULT);
COMMIT;

-- 15
SELECT WRITER_NM, COUNT(WRITER_NM)
FROM TB_WRITER
GROUP BY WRITER_NM HAVING COUNT(WRITER_NM)>=2;

-- 16
UPDATE TB_BOOK_AUTHOR
SET COMPOSE_TYPE = '지음'
WHERE COMPOSE_TYPE IS NULL;

-- 17
SELECT WRITER_NM, OFFICE_TELNO
FROM TB_WRITER
WHERE SUBSTR(HOME_TELNO,1,2) = 02
AND SUBSTR(OFFICE_TELNO,1,4) LIKE '___-%';

-- 18
SELECT WRITER_NM, REGIST_DATE
FROM TB_WRITER
WHERE REGIST_DATE <='1975-01-01'
ORDER BY 1;

-- 19
SELECT BOOK_NM, PRICE, CASE WHEN STOCK_QTY < 5 THEN '추가주문필요'
                            ELSE '소량보유' END 재고상태
FROM TB_BOOK
WHERE PUBLISHER_NM = '황금가지'
AND STOCK_QTY < 10;

-- 20
SELECT B.BOOK_NM 도서명, I.WRITER_NM 저자, J.WRITER_NM 역자
FROM TB_BOOK_AUTHOR BA, TB_BOOK_TRANSLATOR BT, TB_WRITER I, TB_WRITER J, TB_BOOK B
WHERE BA.BOOK_NO = BT.BOOK_NO
AND I.WRITER_NO = BA.WRITER_NO
AND J.WRITER_NO = BT.WRITER_NO
AND B.BOOK_NO = BA.BOOK_NO
AND BA.BOOK_NO = (SELECT BOOK_NO
                  FROM TB_BOOK
                  WHERE BOOK_NM = '아타트롤');

-- 21
SELECT BOOK_NM 도서명, STOCK_QTY 재고수량, PRICE "가격(Org)", 0.8*PRICE "가격(New)"
FROM TB_BOOK
WHERE ISSUE_DATE < '1990/07/22'
AND STOCK_QTY >= 90
ORDER BY 2 DESC, 4 DESC, 1;







