-- 1
INSERT INTO TB_CLASS_TYPE VALUES ('01', '전공필수');
INSERT INTO TB_CLASS_TYPE VALUES ('02', '전공선택');
INSERT INTO TB_CLASS_TYPE VALUES ('03', '교양필수');
INSERT INTO TB_CLASS_TYPE VALUES ('04', '교양선택');
INSERT INTO TB_CLASS_TYPE VALUES ('05', '논문지도');

-- 2
CREATE TABLE TB_학생일반정보
AS (SELECT STUDENT_NO 학번, STUDENT_NAME 학생이름, STUDENT_ADDRESS 주소
    FROM TB_STUDENT);

-- 3
CREATE TABLE TB_국어국문학과
AS (SELECT STUDENT_NO 학번, STUDENT_NAME 학생이름, EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN,1,6))) 출생년도, PROFESSOR_NAME 교수이름
    FROM TB_STUDENT S
    JOIN TB_PROFESSOR P ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
    WHERE S.DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_DEPARTMENT WHERE DEPARTMENT_NAME = '국어국문학과'));
DROP TABLE TB_국어국문학과;























