-- TXT.1
SELECT EMP_ID 사번, EMP_NAME 사원명, SALARY 급여, JOB_NAME 직급명, DEPT_TITLE 부서명, LOCAL_NAME 근무지역명
FROM EMPLOYEE E, JOB J, DEPARTMENT D, LOCATION L
WHERE DEPT_CODE = DEPT_ID
AND E.JOB_CODE = J.JOB_CODE
AND LOCATION_ID = LOCAL_CODE
AND JOB_NAME = '대리' AND LOCAL_NAME LIKE 'ASIA%';

SELECT EMP_ID 사번, EMP_NAME 사원명, JOB_NAME 직급명, DEPT_TITLE 부서명, LOCAL_NAME 근무지역명, SALARY 급여
FROM EMPLOYEE E
JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
JOIN DEPARTMENT D ON DEPT_CODE = DEPT_ID
JOIN LOCATION L ON D.LOCATION_ID = L.LOCAL_CODE
WHERE JOB_NAME = '대리' AND LOCAL_NAME LIKE 'ASIA%';

-- TXT.2
SELECT EMP_NAME 사원명, EMP_NO 주민번호, DEPT_TITLE 부서명, JOB_NAME 직급명
FROM EMPLOYEE E, DEPARTMENT D, JOB J
WHERE DEPT_ID = DEPT_CODE
AND E.JOB_CODE = J.JOB_CODE
AND EMP_NO LIKE '7%'
AND SUBSTR(EMP_NO,8,1) = 2
AND EMP_NAME LIKE '전%';

SELECT EMP_NAME 사원명, EMP_NO 주민번호, DEPT_TITLE 부서명, JOB_NAME 직급명
FROM EMPLOYEE E
JOIN DEPARTMENT D ON DEPT_ID = DEPT_CODE
JOIN JOB J USING (JOB_CODE)
WHERE EMP_NO LIKE '7%'
AND SUBSTR(EMP_NO,8,1) = 2
AND EMP_NAME LIKE '전%';

-- TXT.3
SELECT EMP_ID 사번, EMP_NAME 사원명, JOB_NAME 직급명
FROM EMPLOYEE E, JOB J
WHERE E.JOB_CODE = J.JOB_CODE
AND EMP_NAME LIKE '%형%';

SELECT EMP_ID 사번, EMP_NAME 사원명, JOB_NAME 직급명
FROM EMPLOYEE E
JOIN JOB J USING(JOB_CODE)
WHERE EMP_NAME LIKE '%형%';

-- TXT.4
SELECT EMP_NAME 사원명, JOB_NAME 직급명, DEPT_CODE 부서코드, DEPT_TITLE 부서명
FROM EMPLOYEE E, JOB J, DEPARTMENT D
WHERE E.DEPT_CODE = D.DEPT_ID AND E.JOB_CODE = J.JOB_CODE
AND DEPT_TITLE LIKE '해외영업%';

SELECT EMP_NAME 사원명, JOB_NAME 직급명, DEPT_CODE 부서코드, DEPT_TITLE 부서명
FROM EMPLOYEE E
JOIN JOB J USING (JOB_CODE)
JOIN DEPARTMENT D ON DEPT_CODE = DEPT_ID
WHERE DEPT_TITLE LIKE '해외영업%';

-- TXT.5
SELECT EMP_NAME 사원명, BONUS 보너스, SALARY*12 연봉, DEPT_TITLE 부서명, LOCAL_NAME 근무지역명
FROM EMPLOYEE E, DEPARTMENT D, LOCATION L
WHERE DEPT_CODE = DEPT_ID AND L.LOCAL_CODE = D.LOCATION_ID
AND BONUS IS NOT NULL;

SELECT EMP_NAME 사원명, BONUS 보너스, SALARY*12 연봉, DEPT_TITLE 부서명, LOCAL_NAME 근무지역명
FROM EMPLOYEE E
JOIN DEPARTMENT D ON DEPT_CODE = DEPT_ID
JOIN LOCATION L ON LOCAL_CODE = LOCATION_ID
WHERE BONUS IS NOT NULL;

-- TXT.6
SELECT EMP_NAME 사원명, JOB_NAME 직급명, DEPT_TITLE 부서명, LOCAL_NAME 근무지역명
FROM EMPLOYEE E, DEPARTMENT D, LOCATION L, JOB J
WHERE DEPT_CODE = DEPT_ID AND E.JOB_CODE = J.JOB_CODE AND LOCAL_CODE = LOCATION_ID
AND DEPT_CODE IS NOT NULL;

SELECT EMP_NAME 사원명, JOB_NAME 직급명, DEPT_TITLE 부서명, LOCAL_NAME 근무지역명
FROM EMPLOYEE E
JOIN DEPARTMENT D ON DEPT_CODE = DEPT_ID
JOIN LOCATION L ON LOCAL_CODE = LOCATION_ID
JOIN JOB J USING (JOB_CODE)
WHERE DEPT_CODE IS NOT NULL;

-- TXT.7
SELECT EMP_NAME 사원명, DEPT_TITLE 부서명, LOCAL_NAME 근무지역명, NATIONAL_NAME 근무국가명
FROM EMPLOYEE E, DEPARTMENT D, LOCATION L, NATIONAL N
WHERE DEPT_CODE = DEPT_ID AND LOCAL_CODE = LOCATION_ID AND L.NATIONAL_CODE = N.NATIONAL_CODE
AND (NATIONAL_NAME = '한국' OR NATIONAL_NAME = '일본');

SELECT EMP_NAME 사원명, DEPT_TITLE 부서명, LOCAL_NAME 근무지역명, NATIONAL_NAME 근무국가명
FROM EMPLOYEE E
JOIN DEPARTMENT D ON DEPT_CODE = DEPT_ID
JOIN LOCATION L ON LOCAL_CODE = LOCATION_ID
JOIN NATIONAL N ON L.NATIONAL_CODE = N.NATIONAL_CODE
WHERE NATIONAL_NAME = '한국' OR NATIONAL_NAME = '일본';

-- TXT.8
SELECT EMP_NAME 사원명, E.JOB_CODE 직급코드 , JOB_NAME 직급명, SALARY 급여
FROM EMPLOYEE E, JOB J
WHERE E.JOB_CODE = J.JOB_CODE
AND (E.JOB_CODE IN ('J4', 'J7'))
AND BONUS IS NULL;

SELECT EMP_NAME 사원명, E.JOB_CODE 직급코드, JOB_NAME 직급명, SALARY 급여
FROM EMPLOYEE E
JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
WHERE E.JOB_CODE IN ('J4', 'J7') AND BONUS IS NULL;

-- TXT.9
SELECT EMP_ID 사번, EMP_NAME 사원명, DEPT_TITLE 직급명, CASE WHEN SAL_LEVEL = 'S1' OR SAL_LEVEL = 'S2' THEN '고급'
        WHEN SAL_LEVEL = 'S3' OR SAL_LEVEL = 'S4' THEN '중급'
        WHEN SAL_LEVEL = 'S5' OR SAL_LEVEL = 'S6' THEN '초급' END 구분
FROM EMPLOYEE E, DEPARTMENT D, SAL_GRADE
WHERE DEPT_CODE = DEPT_ID(+) AND SALARY BETWEEN MIN_SAL AND MAX_SAL;

SELECT EMP_ID 사번, EMP_NAME 사원명, DEPT_TITLE 직급명, CASE WHEN SAL_LEVEL = 'S1' OR SAL_LEVEL = 'S2' THEN '고급'
        WHEN SAL_LEVEL = 'S3' OR SAL_LEVEL = 'S4' THEN '중급'
        WHEN SAL_LEVEL = 'S5' OR SAL_LEVEL = 'S6' THEN '초급' END 구분
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D ON DEPT_CODE = DEPT_ID
LEFT JOIN SAL_GRADE ON SALARY BETWEEN MIN_SAL AND MAX_SAL;

-- TXT.10
SELECT DEPT_TITLE, TO_CHAR(SUM(SALARY),'99,999,999')
FROM EMPLOYEE E, DEPARTMENT D
WHERE DEPT_CODE = DEPT_ID
GROUP BY DEPT_TITLE HAVING SUM(SALARY) >= 10000000;


SELECT DEPT_TITLE, TO_CHAR(SUM(SALARY),'99,999,999')
FROM EMPLOYEE E
JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
GROUP BY DEPT_TITLE HAVING SUM(SALARY) >= 10000000;

-- TXT.11
SELECT DEPT_TITLE, ROUND(AVG(SALARY), 0)
FROM EMPLOYEE E, DEPARTMENT D
WHERE DEPT_CODE = DEPT_ID(+)
GROUP BY DEPT_TITLE;

SELECT DEPT_TITLE, ROUND(AVG(SALARY), 0)
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D ON DEPT_CODE = DEPT_ID
GROUP BY DEPT_TITLE;
