-- 1
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS 주소지
FROM TB_STUDENT
ORDER BY 1;

-- 2
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC;

-- 3
SELECT STUDENT_NAME 학생이름, STUDENT_NO 학번, STUDENT_ADDRESS "거주지 주소"
FROM (SELECT * FROM TB_STUDENT WHERE SUBSTR(STUDENT_ADDRESS,1,3) IN ('경기도', '강원도'))
WHERE SUBSTR(STUDENT_NO,1,1) = '9'
ORDER BY 1;

-- 4
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_DEPARTMENT WHERE DEPARTMENT_NAME = '법학과')
ORDER BY 2;

-- 5
SELECT STUDENT_NO, TO_CHAR(POINT,'9.99')
FROM TB_GRADE
WHERE CLASS_NO = 'C3118100'
AND TERM_NO = '200402'
ORDER BY 2 DESC, 1;

-- 6
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT S, TB_DEPARTMENT D
WHERE S.DEPARTMENT_NO = D.DEPARTMENT_NO
ORDER BY 2;

-- 7
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS C, TB_DEPARTMENT D
WHERE C.DEPARTMENT_NO = D.DEPARTMENT_NO;

-- 8
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS C
JOIN TB_CLASS_PROFESSOR CP USING (CLASS_NO)
JOIN TB_PROFESSOR USING (PROFESSOR_NO)
ORDER BY 2;

-- 9
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS C
JOIN TB_CLASS_PROFESSOR CP USING (CLASS_NO)
JOIN TB_PROFESSOR P USING (PROFESSOR_NO)
JOIN TB_DEPARTMENT D ON P.DEPARTMENT_NO = D.DEPARTMENT_NO
WHERE CATEGORY = '인문사회';

-- 10
SELECT STUDENT_NO 학번, STUDENT_NAME "학생 이름", ROUND(AVG(POINT),1) "전체 평점"
FROM (SELECT * FROM TB_STUDENT WHERE DEPARTMENT_NO = 
(SELECT DEPARTMENT_NO FROM TB_DEPARTMENT WHERE DEPARTMENT_NAME = '음악학과')) A
JOIN TB_GRADE G USING (STUDENT_NO) 
GROUP BY STUDENT_NO, STUDENT_NAME
ORDER BY 1;

-- 11
SELECT DEPARTMENT_NAME 학과이름, STUDENT_NAME 학생명, PROFESSOR_NAME 지도교수이름
FROM TB_STUDENT S, TB_DEPARTMENT D, TB_PROFESSOR P
WHERE S.DEPARTMENT_NO = D.DEPARTMENT_NO
AND PROFESSOR_NO = COACH_PROFESSOR_NO
AND STUDENT_NO = 'A313047';

-- 12
SELECT STUDENT_NAME, TERM_NO "TERM_NAME"
FROM TB_STUDENT S, TB_GRADE G
WHERE S.STUDENT_NO = G.STUDENT_NO
AND SUBSTR(TERM_NO,1,4) = '2007'
AND CLASS_NO = (SELECT CLASS_NO FROM TB_CLASS WHERE CLASS_NAME = '인간관계론')
ORDER BY 1;

-- 13
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS T, TB_DEPARTMENT D
WHERE T.DEPARTMENT_NO = D.DEPARTMENT_NO
AND CLASS_NO IN (SELECT CLASS_NO FROM TB_CLASS MINUS SELECT CLASS_NO FROM TB_CLASS_PROFESSOR)
AND T.DEPARTMENT_NO IN (SELECT DEPARTMENT_NO FROM TB_DEPARTMENT WHERE CATEGORY = '예체능')
ORDER BY 1;

-- 14
SELECT STUDENT_NAME 학생이름, NVL(PROFESSOR_NAME,'지도교수 미지정') 지도교수
FROM TB_STUDENT S, TB_PROFESSOR P
WHERE S.COACH_PROFESSOR_NO = P.PROFESSOR_NO(+)
AND S.DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_DEPARTMENT WHERE DEPARTMENT_NAME = '서반아어학과')
ORDER BY STUDENT_NO;

-- 15
SELECT S.STUDENT_NO 학번, STUDENT_NAME 이름, DEPARTMENT_NAME "학과 이름", ROUND(AVG(POINT),8) 평점
FROM (SELECT * FROM TB_STUDENT WHERE ABSENCE_YN = 'N') S, TB_GRADE G, TB_DEPARTMENT D
WHERE S.DEPARTMENT_NO = D.DEPARTMENT_NO
AND S.STUDENT_NO = G.STUDENT_NO
GROUP BY S.STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME HAVING AVG(POINT) >= 4
ORDER BY S.STUDENT_NO;

-- 16
SELECT C.CLASS_NO, CLASS_NAME, ROUND(AVG(POINT),8)
FROM TB_CLASS C, TB_GRADE G
WHERE C.CLASS_NO = G.CLASS_NO
AND DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_DEPARTMENT WHERE DEPARTMENT_NAME = '환경조경학과')
AND SUBSTR(CLASS_TYPE,1,2) = '전공'
GROUP BY C.CLASS_NO, CLASS_NAME
ORDER BY 1;

-- 17
SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_STUDENT WHERE STUDENT_NAME = '최경희');

-- 18
SELECT STUDENT_NO, STUDENT_NAME
FROM (SELECT ROWNUM, STUDENT_NO, STUDENT_NAME
FROM (SELECT S.STUDENT_NO, STUDENT_NAME, AVG(POINT)
FROM TB_STUDENT S, TB_GRADE G
WHERE S.STUDENT_NO = G.STUDENT_NO
AND DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_DEPARTMENT WHERE DEPARTMENT_NAME = '국어국문학과')
GROUP BY S.STUDENT_NO, STUDENT_NAME
ORDER BY 3 DESC))
WHERE ROWNUM = 1;

-- 19
SELECT DEPARTMENT_NAME, ROUND(AVG(POINT),1)
FROM TB_CLASS C, TB_DEPARTMENT D, TB_GRADE G
WHERE C.DEPARTMENT_NO = D.DEPARTMENT_NO
AND C.CLASS_NO = G.CLASS_NO
AND C.DEPARTMENT_NO IN (SELECT DEPARTMENT_NO FROM TB_DEPARTMENT
WHERE CATEGORY = (SELECT CATEGORY FROM TB_DEPARTMENT WHERE DEPARTMENT_NAME = '환경조경학과'))
AND SUBSTR(C.CLASS_TYPE,1,2) = '전공'
GROUP BY DEPARTMENT_NAME
ORDER BY 1;








