-- FUNCTION 1
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 002
ORDER BY 3;

-- FUNCTION 2
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;

-- FUNCTION 3
SELECT PROFESSOR_NAME 교수이름, 120 - SUBSTR(PROFESSOR_SSN, 1, 2) 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = 1
ORDER BY 2;

-- FUNCTION 4 
SELECT SUBSTR(PROFESSOR_NAME, 2, 2) 이름
FROM TB_PROFESSOR;

-- FUNCTION 5 
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE (EXTRACT(YEAR FROM ENTRANCE_DATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN, 1, 6)))) >= 20;

-- FUNCTION 6
SELECT TO_CHAR(TO_DATE(201225), 'DAY') FROM DUAL;

-- FUNCTION 7
SELECT TO_DATE('99/10/11', 'YY/MM/DD'), 
        TO_DATE('49/10/11', 'YY/MM/DD'), 
        TO_DATE('99/10/11', 'RR/MM/DD'),
        TO_DATE('49/10/11', 'RR/MM/DD') FROM DUAL;

-- FUNCTION 8
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO NOT LIKE 'A%';

-- FUNCTION 9
SELECT ROUND(AVG(POINT), 1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

-- FUNCTION 10
-- FUNCTION 11
-- FUNCTION 12
-- FUNCTION 13
-- FUNCTION 14 
-- FUNCTION 15
-- END