DROP TABLE MEMBER;

CREATE TABLE MEMBER(
    USERNO NUMBER PRIMARY KEY,
    USERID VARCHAR2(15) NOT NULL UNIQUE,
    USERPWD VARCHAR2(20) NOT NULL,
    USERNAME VARCHAR2(20) NOT NULL,
    GENDER CHAR(1) CHECK(GENDER IN ('M', 'F')),
    AGE NUMBER,
    EMAIL VARCHAR2(30),
    PHONE CHAR(11),
    ADDRESS VARCHAR2(100),
    HOBBY VARCHAR2(50),
    ENROLLDATE DATE DEFAULT SYSDATE
);

SELECT * FROM MEMBER;

DROP SEQUENCE SEQ_USER_NO;
CREATE SEQUENCE SEQ_USER_NO;

INSERT INTO MEMBER
VALUES(SEQ_USER_NO.NEXTVAL, 'admin', '1234', '관리자', 'M', 45, 'admin@naver.com', 
       '01012341111', '서울시 관악구', '잠자기', '2020/06/21');

INSERT INTO MEMBER
VALUES(SEQ_USER_NO.NEXTVAL, 'user01', 'pass01', '홍길동', 'F', 20, NULL, 
       '01011112222', NULL, '영화보기', '2020/07/01');
       
SELECT * FROM MEMBER;
SELECT SEQ_USER_NO.NEXTVAL FROM DUAL;
COMMIT;


